### ISSUE TITLE
localization_it.properties

### ISSUE THREAD

**Issue by gpitasi86** [voidburn/cron-expression-descriptor#1]
Italian translation problem at row 21: 
"EveryHour=every\u0020hour" must be "EveryHour=ogni\u0020ora"

**Comment by gpitasi86** [comment]
thank you,
however the modification has ruined the accented characters of the following translations:

WeekdayNearestDayX0 at row 54
InvalidExpressionFormatTooManyParts at row 69
InvalidFieldExpressionFormat at row 70
InvalidDomDowExpression at row 78
InvalidYearsRangeValue at row 79
InvalidYearFrequencyValue at row 80

I also underline the following errors:
5/10 * * * *  -> Ogni 10 minuti, a partire _**dal al**_ minuto 5 passata l'ora
0 1/10 * * * -> Ogni 10 ore, a partire _**dal alle**_ 01:00

**Comment by voidburn** [comment]
Found them, I didn't see them in the diff because they appear to have been broken before in my project install. Still not clear why this is happening but I have now replaced them with their Unicode entries so that they stay put.

As for the other errors, I changed: 
CommaStartingX0=,\u0020a\u0020partire\u0020dal\u0020%s
CommaStartingX0=,\u0020a\u0020partire\u0020%s

It will still not be grammatically correct, as it will show as "Ogni 10 minuti, a partire al minuto 5 passata l'ora" and "Ogni 10 ore, a partire alle 01:00". Semantically speaking the algorithm cannot understand the difference in use between "al minuto X" and "dal minuto X", in English the same template string is used in both cases and this is why this is happening.

You can test the expected output here: https://bradymholt.github.io/cron-expression-descriptor/?locale=it

Will commit these fixes momentarily. It would help if you could build the library from that commit and confirm that it is working as expected, before I make a new release to maven.

**Comment by josefdgl** [comment]
Perfect, now it works as expected.
Thank you

**Comment by voidburn** [comment]
Release 1.2.2 published to maven, should be available in an hour or two. Thank you for your contribution!
