### ISSUE TITLE
Human readable day field is not the same as the parent C# library for JEE Timer ScheduleExpression

### ISSUE THREAD

**Issue by FWidm** [voidburn/cron-expression-descriptor#7]
Hi I've just noticed that if you for example have the following cron string:

`0 0 13 * * 1` 

the parent c# library returns `At 01:00 PM, only on Monday`
while this one in the default config returns: `At 13:00, only on Sunday` or with 24h display turned off: `At 01:00 PM, only on Sunday`

Afaik 0/7 would be sunday and then 1 should be monday as written for the JEE Timer classes: https://docs.oracle.com/javaee/7/tutorial/ejb-basicexamples004.htm

This leads to 0 being shifted to -1 here in `CronExpressionParser` for a valid JEE expression:

```java
            if (partsCount == 5) {
                if (dowDigits.equals("7")) {
                    dowDigitsAdjusted = "0";
                }
            } else {
                // If the expression has more than 5 parts (which means it includes seconds and/or years), Sunday is specified as 1 and Saturday is specified as 7.
                // To normalize, we bring it back in the 0-6 range.
                //
                // See Quartz cron triggers (http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html)
                dowDigitsAdjusted = String.valueOf(Integer.parseInt(dowDigits) - 1);
            }
```

Would you be willing to support JEE crons as well?

Best regards,

Fabian

**Comment by voidburn** [comment]
Hey, thanks for reporting this issue. I guess I could introduce a setting flag in the options that you can set when you want to enforce the JEE standard, instead of Quartz, for expressions with more than 5 parts. When that is set it would simply remap 7 to 0 and hit the correct ordinal in the Enum exactly the same as it does now for the regular cron expressions.

If you're in a hurry to deploy in your environment you could replace this: 

```
if (partsCount == 5) {
    if (dowDigits.equals("7")) {
        dowDigitsAdjusted = "0";
    }
} else {
    // If the expression has more than 5 parts (which means it includes seconds and/or years), Sunday is specified as 1 and Saturday is specified as 7.
    // To normalize, we bring it back in the 0-6 range.
    //
    // See Quartz cron triggers (http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html)
    dowDigitsAdjusted = String.valueOf(Integer.parseInt(dowDigits) - 1);
}
```

with a forced remapping:

```
if (dowDigits.equals("7")) {
    dowDigitsAdjusted = "0";
}
```

It will mess with Quartz, but since you're not using it it should be ok. Can you please run some tests on your end with this modification and confirm that it works as expected? (both with 6 and 7 part expressions).

Cheers

**Comment by FWidm** [comment]
I'm not in a hurry if you can add a flag this would be amazing as a future feature.

**Comment by voidburn** [comment]
Cool, please let me know if the change I suggested produces exactly what you expect in a JEE environment, then I'll add this to my TODO!

**Comment by FWidm** [comment]
Thanks works as intended in the newly released version :+1:
